export interface ArtifactImageCatalogEntry {
    id: number;
    name: string;
    localImage?: string;
    wikipediaTitle?: string;
    remoteImage?: string;
    status: "ready" | "pending" | "missing";
}

export const artifactImageCatalog: Record<number, ArtifactImageCatalogEntry> = {
    1: {
        id: 1,
        name: "铸客大鼎",
        localImage: "1-cache.jpg",
        status: "ready",
    },
    2: {
        id: 2,
        name: "彩绘季札挂剑图漆盘",
        wikipediaTitle: "吴彩绘季札挂剑图漆盘",
        status: "ready",
    },
    3: {
        id: 3,
        name: "皮胎犀皮漆金铜扣耳杯（2件）",
        wikipediaTitle: "吴皮胎犀皮漆鎏金铜釦耳杯（2件）",
        status: "ready",
    },
    4: {
        id: 4,
        name: "何尊",
        localImage: "4-hezun-official.png",
        status: "ready",
    },
    5: {
        id: 5,
        name: "墙盘",
        localImage: "5-cache.jpg",
        status: "ready",
    },
    6: {
        id: 6,
        name: "㝬簋",
        localImage: "6-cache.jpg",
        status: "ready",
    },
    7: {
        id: 7,
        name: "逨盘",
        localImage: "7-cache.jpg",
        status: "ready",
    },
    8: {
        id: 8,
        name: "太阳神鸟金箔片",
        localImage: "8-cache.jpg",
        status: "ready",
    },
    9: {
        id: 9,
        name: "定窑白釉刻莲花瓣纹龙首净瓶",
        wikipediaTitle: "北宋定窑白釉刻莲花瓣纹龙首净瓶",
        status: "ready",
    },
    10: {
        id: 10,
        name: "透雕神仙故事玉座屏",
        localImage: "10-dingzhou-yuzuoping.jpg",
        status: "ready",
    },
    11: {
        id: 11,
        name: "刺绣佛像供养人",
        wikipediaTitle: "北魏刺绣佛像供养人",
        status: "ready",
    },
    12: {
        id: 12,
        name: "银花双轮十二环锡杖",
        wikipediaTitle: "银花双轮十二环锡杖",
        status: "ready",
    },
    13: {
        id: 13,
        name: "八重宝函",
        localImage: "13-cache.jpg",
        status: "ready",
    },
    14: {
        id: 14,
        name: "鎏金铜浮屠",
        wikipediaTitle: "铜浮屠",
        status: "ready",
    },
    15: {
        id: 15,
        name: "仰韶文化彩陶人形双系瓶",
        wikipediaTitle: "新石器时代仰韶文化彩陶人形双系瓶",
        status: "ready",
    },
    16: {
        id: 16,
        name: "铜奔马",
        localImage: "16-cache.jpg",
        status: "ready",
    },
    17: {
        id: 17,
        name: "展子虔《游春图》卷",
        localImage: "17-cache.jpg",
        status: "ready",
    },
    18: {
        id: 18,
        name: "韩滉《五牛图》卷",
        localImage: "18-official.jpg",
        status: "ready",
    },
    19: {
        id: 19,
        name: "周昉《挥扇仕女图》卷",
        localImage: "19-official.jpg",
        status: "ready",
    },
    20: {
        id: 20,
        name: "周文矩《重屏会棋图》卷",
        localImage: "20-official.jpg",
        status: "ready",
    },
    21: {
        id: 21,
        name: "胡瓌《卓歇图》卷",
        localImage: "21-official.jpg",
        status: "ready",
    },
    22: {
        id: 22,
        name: "顾闳中《韩熙载夜宴图》卷",
        localImage: "22-cache.jpg",
        status: "ready",
    },
    23: {
        id: 23,
        name: "卫贤《高士图》轴",
        localImage: "23-official.jpg",
        status: "ready",
    },
    24: {
        id: 24,
        name: "黄筌《写生珍禽图》卷",
        localImage: "24-official.jpg",
        status: "ready",
    },
    25: {
        id: 25,
        name: "王诜《渔村小雪图》卷",
        localImage: "25-official.jpg",
        status: "ready",
    },
    26: {
        id: 26,
        name: "梁师闵《芦汀密雪图》卷",
        localImage: "26-official.jpg",
        status: "ready",
    },
    27: {
        id: 27,
        name: "祁序《江山牧放图》卷",
        localImage: "27-official.jpg",
        status: "ready",
    },
    28: {
        id: 28,
        name: "李公麟《摹韦偃牧放图》卷",
        localImage: "28-official.jpg",
        status: "ready",
    },
    29: {
        id: 29,
        name: "张择端《清明上河图》卷",
        localImage: "29-cache.jpg",
        status: "ready",
    },
    30: {
        id: 30,
        name: "王希孟《千里江山图》卷",
        localImage: "30-cache.jpg",
        status: "ready",
    },
    31: {
        id: 31,
        name: "马和之《后赤壁赋图》卷",
        localImage: "31-official.jpg",
        status: "ready",
    },
    32: {
        id: 32,
        name: "赵伯骕《万松金阙图》卷",
        localImage: "wansongjinque.jpg",
        status: "ready",
    },
    33: {
        id: 33,
        name: "步辇图",
        localImage: "33-official.jpg",
        status: "ready",
    },
    34: {
        id: 34,
        name: "陆机《平复帖》卷",
        localImage: "34-cache.jpg",
        status: "ready",
    },
    35: {
        id: 35,
        name: "王珣《伯远帖》卷",
        localImage: "35-official.jpg",
        status: "ready",
    },
    36: {
        id: 36,
        name: "冯承素摹王羲之《兰亭序》卷",
        localImage: "36-cache.jpg",
        status: "ready",
    },
    37: {
        id: 37,
        name: "国诠书《善见律》卷",
        localImage: "37-official.jpg",
        status: "ready",
    },
    38: {
        id: 38,
        name: "杜牧《张好好诗》卷",
        localImage: "38-cache.jpg",
        status: "ready",
    },
    39: {
        id: 39,
        name: "杨凝式《神仙起居法帖》卷",
        localImage: "39-official.jpg",
        status: "ready",
    },
    40: {
        id: 40,
        name: "林逋《自书诗》卷",
        localImage: "40-official.jpg",
        status: "ready",
    },
    41: {
        id: 41,
        name: "蔡襄《自书诗》卷",
        localImage: "41-official.jpg",
        status: "ready",
    },
    42: {
        id: 42,
        name: "文彦博《三帖卷》",
        localImage: "42-official.jpg",
        status: "ready",
    },
    43: {
        id: 43,
        name: "黄庭坚《诸上座》卷",
        localImage: "43-official.jpg",
        status: "ready",
    },
    44: {
        id: 44,
        name: "米芾《苕溪诗》卷",
        localImage: "44-official.jpg",
        status: "ready",
    },
    45: {
        id: 45,
        name: "灵鹫纹锦袍",
        localImage: "45-official.png",
        status: "ready",
    },
    46: {
        id: 46,
        name: "永安三年”款青釉堆塑谷仓罐",
        localImage: "46-official.jpg",
        status: "ready",
    },
    47: {
        id: 47,
        name: "青釉凤首龙柄壶",
        localImage: "47-official.png",
        status: "ready",
    },
    48: {
        id: 48,
        name: "鲁山窑黑釉蓝斑腰鼓",
        localImage: "48-official.jpg",
        status: "ready",
    },
    49: {
        id: 49,
        name: "汝窑天青釉弦纹樽",
        localImage: "49-official.png",
        status: "ready",
    },
    50: {
        id: 50,
        name: "官窑弦纹瓶",
        localImage: "50-official.jpg",
        status: "ready",
    },
    51: {
        id: 51,
        name: "钧窑月白釉出戟尊",
        localImage: "51-official.jpg",
        status: "ready",
    },
    52: {
        id: 52,
        name: "登封窑白釉珍珠地划花双虎纹瓶",
        localImage: "dengfengyao.png",
        status: "ready",
    },
    53: {
        id: 53,
        name: "石鼓 (1组10只)",
        localImage: "53-cache.jpg",
        status: "ready",
    },
    54: {
        id: 54,
        name: "拓西岳华山庙碑册 (华阴本)",
        localImage: "54-official.png",
        status: "ready",
    },
    55: {
        id: 55,
        name: "唐写本王仁煦《刊谬补缺切韵》",
        localImage: "55-cache.jpg",
        status: "ready",
    },
    56: {
        id: 56,
        name: "铜立人像",
        localImage: "56-cache.jpg",
        status: "ready",
    },
    57: {
        id: 57,
        name: "金杖",
        wikipediaTitle: "三星堆金杖",
        status: "ready",
    },
    58: {
        id: 58,
        name: "韩琦《行楷信礼卷》",
        wikipediaTitle: "行楷信札卷",
        status: "ready",
    },
    59: {
        id: 59,
        name: "战国水晶杯",
        localImage: "59-official.jpg",
        status: "ready",
    },
    60: {
        id: 60,
        name: "刘胜金缕玉衣",
        localImage: "60-official.png",
        status: "ready",
    },
    61: {
        id: 61,
        name: "长信宫灯",
        localImage: "61-official.jpg",
        status: "ready",
    },
    62: {
        id: 62,
        name: "中山王铁足铜鼎",
        localImage: "62-official.jpg",
        status: "ready",
    },
    63: {
        id: 63,
        name: "错金银镶松石狩猎纹铜伞铤",
        localImage: "63-official.jpg",
        status: "ready",
    },
    64: {
        id: 64,
        name: "错金银四龙四凤铜方案",
        localImage: "64-official.jpg",
        status: "ready",
    },
    65: {
        id: 65,
        name: "白釉绿彩长颈瓶",
        localImage: "65-official.jpg",
        status: "ready",
    },
    66: {
        id: 66,
        name: "淅川出土铜禁",
        localImage: "66-official.jpeg",
        status: "ready",
    },
    67: {
        id: 67,
        name: "越王勾践剑",
        localImage: "67-official.jpg",
        status: "ready",
    },
    68: {
        id: 68,
        name: "多节活环套练玉佩",
        localImage: "68-official.jpg",
        status: "ready",
    },
    69: {
        id: 69,
        name: "彩绘乐舞图鸳鸯形漆盒",
        localImage: "69-official.png",
        status: "ready",
    },
    70: {
        id: 70,
        name: "云梦睡虎地秦简《语书》",
        localImage: "70-official.jpg",
        status: "ready",
    },
    71: {
        id: 71,
        name: "彩漆木雕小座屏",
        localImage: "71-official.jpeg",
        status: "ready",
    },
    72: {
        id: 72,
        name: "曾侯乙编钟",
        localImage: "72-official.jpg",
        status: "ready",
    },
    73: {
        id: 73,
        name: "曾侯乙墓外棺",
        localImage: "73-official.png",
        status: "ready",
    },
    74: {
        id: 74,
        name: "曾侯乙青铜尊盘",
        localImage: "74-official.jpeg",
        status: "ready",
    },
    75: {
        id: 75,
        name: "大玉戈",
        localImage: "75-official.jpeg",
        status: "ready",
    },
    76: {
        id: 76,
        name: "秦简《数》",
        localImage: "76-official.jpg",
        status: "ready",
    },
    77: {
        id: 77,
        name: "神兽纹玉樽",
        wikipediaTitle: "神兽纹玉樽",
        status: "ready",
    },
    78: {
        id: 78,
        name: "长沙窑青釉褐彩贴花人物纹壶",
        wikipediaTitle: "唐长沙窑青釉褐彩贴花人物纹壶",
        status: "ready",
    },
    79: {
        id: 79,
        name: "大禾方鼎",
        wikipediaTitle: "大禾方鼎",
        status: "ready",
    },
    80: {
        id: 80,
        name: "识文彩绘盝顶长方形漆奁",
        wikipediaTitle: "识文彩绘盝顶长方形漆奁",
        status: "ready",
    },
    81: {
        id: 81,
        name: "黑漆朱绘六博具",
        wikipediaTitle: "黑漆朱绘六博具",
        status: "ready",
    },
    82: {
        id: 82,
        name: "马王堆汉慕帛书《周易》",
        localImage: "82-cache.jpg",
        status: "ready",
    },
    83: {
        id: 83,
        name: "人物御龙帛画",
        wikipediaTitle: "人物御龙帛画",
        status: "ready",
    },
    84: {
        id: 84,
        name: "人物龙凤帛画",
        wikipediaTitle: "人物龙凤帛画",
        status: "ready",
    },
    85: {
        id: 85,
        name: "直裾素纱禅衣",
        localImage: "85-plain-gauze-gown-official.jpg",
        status: "ready",
    },
    86: {
        id: 86,
        name: "马王堆一号墓木棺椁",
        wikipediaTitle: "马王堆一号墓木棺椁",
        status: "ready",
    },
    87: {
        id: 87,
        name: "马王堆一号墓T型帛画",
        localImage: "87-cache.jpg",
        status: "ready",
    },
    88: {
        id: 88,
        name: "官窑贯耳尊",
        wikipediaTitle: "北宋官窑贯耳尊",
        status: "ready",
    },
    89: {
        id: 89,
        name: "青花釉里红瓷仓",
        wikipediaTitle: "青花釉里红瓷仓",
        status: "ready",
    },
    90: {
        id: 90,
        name: "郭店楚简《老子 (甲、乙、丙) 》",
        wikipediaTitle: "战国郭店楚简《老子（甲、乙、丙）》",
        status: "ready",
    },
    91: {
        id: 91,
        name: "董源《夏景山口待渡图》卷",
        wikipediaTitle: "夏景山口待渡图",
        status: "ready",
    },
    92: {
        id: 92,
        name: "欧阳询《梦奠帖》卷",
        wikipediaTitle: "梦奠帖",
        status: "ready",
    },
    93: {
        id: 93,
        name: "唐人《摹王羲之一门书翰》卷",
        wikipediaTitle: "摹王羲之一门书翰",
        status: "ready",
    },
    94: {
        id: 94,
        name: "赵佶《草书千字文》卷",
        wikipediaTitle: "趙佶《草書千字文》",
        status: "ready",
    },
    95: {
        id: 95,
        name: "耀州窑摩羯形水孟",
        wikipediaTitle: "五代耀州窑摩羯形水盂",
        status: "ready",
    },
    96: {
        id: 96,
        name: "鸭形玻璃注",
        wikipediaTitle: "鸭形玻璃注",
        status: "ready",
    },
    97: {
        id: 97,
        name: "红山文化女神像",
        wikipediaTitle: "红山文化女神像",
        status: "ready",
    },
    98: {
        id: 98,
        name: "越窑青釉褐彩云纹五足炉",
        wikipediaTitle: "唐越窑青釉褐彩云纹五足炉",
        status: "ready",
    },
    99: {
        id: 99,
        name: "七孔玉刀",
        wikipediaTitle: "七孔玉刀",
        status: "ready",
    },
    100: {
        id: 100,
        name: "朱然墓出土漆木屐",
        wikipediaTitle: "朱然墓出土漆木屐",
        status: "ready",
    },
    101: {
        id: 101,
        name: "朱然墓出土贵族生活图漆盘",
        wikipediaTitle: "朱然墓出土贵族生活图漆盘",
        status: "ready",
    },
    102: {
        id: 102,
        name: "茂陵石雕",
        wikipediaTitle: "茂陵石雕",
        status: "ready",
    },
    103: {
        id: 103,
        name: "摇钱树",
        wikipediaTitle: "搖錢樹",
        status: "ready",
    },
    104: {
        id: 104,
        name: "错金银镶嵌丝网套铜壶",
        wikipediaTitle: "错金银镶嵌丝网套铜壶",
        status: "ready",
    },
    105: {
        id: 105,
        name: "青釉神兽尊",
        wikipediaTitle: "西晋青釉神兽尊",
        status: "ready",
    },
    106: {
        id: 106,
        name: "竹林七贤砖印模画",
        wikipediaTitle: "竹林七贤砖印模画",
        status: "ready",
    },
    107: {
        id: 107,
        name: "王齐翰《勘书图》卷",
        wikipediaTitle: "勘书图",
        status: "ready",
    },
    108: {
        id: 108,
        name: "青釉褐彩羽人纹双系壶",
        wikipediaTitle: "吴青釉褐彩羽人纹双系壶",
        status: "ready",
    },
    109: {
        id: 109,
        name: "青花萧何月下追韩信图梅瓶",
        wikipediaTitle: "元青花萧何月下追韩信图梅瓶",
        status: "ready",
    },
    110: {
        id: 110,
        name: "西夏文佛经《吉祥遍至口和本续》纸本",
        wikipediaTitle: "吉祥遍至口和本续",
        status: "ready",
    },
    111: {
        id: 111,
        name: "铜车马",
        localImage: "111-cache.jpg",
        status: "ready",
    },
    112: {
        id: 112,
        name: "红地云珠日天锦",
        wikipediaTitle: "红地云珠日天锦",
        status: "ready",
    },
    113: {
        id: 113,
        name: "简《金滕》",
        wikipediaTitle: "清华简《金滕》",
        status: "ready",
    },
    114: {
        id: 114,
        name: "大汶口文化象牙梳",
        localImage: "114-official.jpg",
        status: "ready",
    },
    115: {
        id: 115,
        name: "大汶口文化彩陶八角星纹豆",
        wikipediaTitle: "新石器时代大汶口文化彩陶八角星纹豆",
        status: "ready",
    },
    116: {
        id: 116,
        name: "晋侯夫人组玉佩",
        wikipediaTitle: "西周晋侯夫人组玉佩",
        status: "ready",
    },
    117: {
        id: 117,
        name: "晋侯鸟尊",
        wikipediaTitle: "晋侯鸟尊",
        status: "ready",
    },
    118: {
        id: 118,
        name: "龙纹兜觥",
        wikipediaTitle: "商龙纹兜觥",
        status: "ready",
    },
    119: {
        id: 119,
        name: "司马金龙墓出土漆屏",
        wikipediaTitle: "北魏司马金龙墓漆屏",
        status: "ready",
    },
    120: {
        id: 120,
        name: "涅槃变相碑",
        wikipediaTitle: "北齐涅槃变相碑",
        status: "ready",
    },
    121: {
        id: 121,
        name: "常阳天尊石像",
        wikipediaTitle: "北齐常阳天尊造像",
        status: "ready",
    },
    122: {
        id: 122,
        name: "娄睿墓鞍马出行图壁画",
        wikipediaTitle: "北齐娄叡墓鞍马出行图",
        status: "ready",
    },
    123: {
        id: 123,
        name: "耀州窑青釉刻花提梁倒流壶",
        localImage: "123-official.png",
        status: "ready",
    },
    124: {
        id: 124,
        name: "三彩骆驼载乐俑",
        localImage: "124-official.png",
        status: "ready",
    },
    125: {
        id: 125,
        name: "“皇后之玺”玉玺",
        localImage: "125-official.png",
        status: "ready",
    },
    126: {
        id: 126,
        name: "章怀太子墓打马球图壁画",
        localImage: "126-official.png",
        status: "ready",
    },
    127: {
        id: 127,
        name: "章怀太子墓狩猎出行图壁画",
        localImage: "127-official.png",
        status: "ready",
    },
    128: {
        id: 128,
        name: "懿德太子墓阙楼仪仗图",
        localImage: "128-official.png",
        status: "ready",
    },
    129: {
        id: 129,
        name: "永泰公主墓宫女图壁画",
        localImage: "129-official.jpg",
        status: "ready",
    },
    130: {
        id: 130,
        name: "舞马衔杯仿皮囊式银壶",
        localImage: "130-cache.jpg",
        status: "ready",
    },
    131: {
        id: 131,
        name: "镶金兽首玛瑙杯",
        localImage: "131-agate-cup-official.png",
        status: "ready",
    },
    132: {
        id: 132,
        name: "淳化大鼎",
        wikipediaTitle: "淳化大鼎",
        status: "ready",
    },
    133: {
        id: 133,
        name: "孙位《高逸图》卷",
        wikipediaTitle: "高逸图",
        status: "ready",
    },
    134: {
        id: 134,
        name: "怀素《苦笋帖》卷",
        localImage: "134-cache.jpg",
        status: "ready",
    },
    135: {
        id: 135,
        name: "王安石《楞严经旨要》卷",
        wikipediaTitle: "楞严经旨要",
        status: "ready",
    },
    136: {
        id: 136,
        name: "商鞅方升",
        wikipediaTitle: "商鞅方升",
        status: "ready",
    },
    137: {
        id: 137,
        name: "曹全碑初拓本 (“因”字不损本)",
        wikipediaTitle: "明初拓曹全碑册",
        status: "ready",
    },
    138: {
        id: 138,
        name: "楚简《孔子诗论》",
        wikipediaTitle: "战国上博楚竹书《孔子诗论》",
        status: "ready",
    },
    139: {
        id: 139,
        name: "大克鼎",
        wikipediaTitle: "大克鼎",
        status: "ready",
    },
    140: {
        id: 140,
        name: "西周晋侯苏钟 (一套16件）",
        wikipediaTitle: "西周晋侯苏钟",
        status: "ready",
    },
    141: {
        id: 141,
        name: "伯矩鬲",
        wikipediaTitle: "伯矩鬲",
        status: "ready",
    },
    142: {
        id: 142,
        name: "三星堆出土玉边璋",
        wikipediaTitle: "三星堆出土玉边璋",
        status: "ready",
    },
    143: {
        id: 143,
        name: "青铜神树",
        localImage: "143-cache.jpg",
        status: "ready",
    },
    144: {
        id: 144,
        name: "越窑莲花式托盏",
        wikipediaTitle: "五代越窑莲花式托盏",
        status: "ready",
    },
    145: {
        id: 145,
        name: "木雕真珠舍利宝幢 (含木函）",
        wikipediaTitle: "木雕真珠舍利宝幢",
        status: "ready",
    },
    146: {
        id: 146,
        name: "白釉龙柄双联传瓶",
        wikipediaTitle: "北齐白釉龙柄双联传瓶",
        status: "ready",
    },
    147: {
        id: 147,
        name: "太保鼎",
        wikipediaTitle: "太保鼎",
        status: "ready",
    },
    148: {
        id: 148,
        name: "唐昭陵六骏石刻 (什伐赤、白蹄乌、特勒骠、青骓4幅)",
        wikipediaTitle: "昭陵六骏",
        status: "ready",
    },
    149: {
        id: 149,
        name: "大秦景教流行中国碑",
        wikipediaTitle: "大秦景教流行中国碑",
        status: "ready",
    },
    150: {
        id: 150,
        name: "景云铜钟",
        localImage: "150-cache.jpg",
        status: "ready",
    },
    151: {
        id: 151,
        name: "彩绘人物车马镜",
        wikipediaTitle: "战国彩绘人物车马镜",
        status: "ready",
    },
    152: {
        id: 152,
        name: "“统领释教大元国师之印”龙钮玉印",
        wikipediaTitle: "统领释教大元国师之印",
        status: "ready",
    },
    153: {
        id: 153,
        name: "铜屏风构件5件",
        wikipediaTitle: "铜屏风构件5件",
        status: "ready",
    },
    154: {
        id: 154,
        name: "角形玉杯",
        wikipediaTitle: "角形玉杯",
        status: "ready",
    },
    155: {
        id: 155,
        name: "方格兽纹锦",
        wikipediaTitle: "北朝方格兽纹锦",
        status: "ready",
    },
    156: {
        id: 156,
        name: "“五星出东方利中国”护膊",
        wikipediaTitle: "“五星出东方利中国”护膊",
        status: "ready",
    },
    157: {
        id: 157,
        name: "红地对人兽树纹罽袍",
        wikipediaTitle: "红地对人兽树纹罽袍",
        status: "ready",
    },
    158: {
        id: 158,
        name: "长沙窑青釉褐蓝彩双系罐",
        wikipediaTitle: "唐长沙窑青釉褐蓝彩双系罐",
        status: "ready",
    },
    159: {
        id: 159,
        name: "蓝釉白龙纹梅瓶",
        wikipediaTitle: "元蓝釉白龙纹梅瓶",
        status: "ready",
    },
    160: {
        id: 160,
        name: "莲鹤铜方壶",
        localImage: "160-official.png",
        status: "ready",
    },
    161: {
        id: 161,
        name: "杀人祭柱场面贮贝器",
        wikipediaTitle: "杀人祭柱场面贮贝器",
        status: "ready",
    },
    162: {
        id: 162,
        name: "良渚文化神人兽面纹玉钺",
        wikipediaTitle: "良渚文化神人兽面纹玉钺",
        status: "ready",
    },
    163: {
        id: 163,
        name: "河姆渡文化双鸟朝阳纹象牙雕刻器",
        wikipediaTitle: "河姆渡遗址双鸟朝阳纹牙雕",
        status: "ready",
    },
    164: {
        id: 164,
        name: "河姆渡出土朱漆碗",
        wikipediaTitle: "河姆渡出土朱漆碗",
        status: "ready",
    },
    165: {
        id: 165,
        name: "河姆渡出土陶灶",
        wikipediaTitle: "河姆渡出土陶灶",
        status: "ready",
    },
    166: {
        id: 166,
        name: "良渚出土玉琮王",
        wikipediaTitle: "良渚玉琮王",
        status: "ready",
    },
    167: {
        id: 167,
        name: "龟负论语玉烛酒筹銮金银筒",
        wikipediaTitle: "清龟负“论语玉烛”酒筹鎏金银筒",
        status: "ready",
    },
    168: {
        id: 168,
        name: "青釉仰覆莲花尊",
        localImage: "168-official.jpg",
        status: "ready",
    },
    169: {
        id: 169,
        name: "包金镶玉嵌琉璃银带钩",
        localImage: "169-official.png",
        status: "ready",
    },
    170: {
        id: 170,
        name: "四羊方尊",
        localImage: "170-official.jpg",
        status: "ready",
    },
    171: {
        id: 171,
        name: "“赤乌十四年”款青釉虎子",
        localImage: "171-official.jpg",
        status: "ready",
    },
    172: {
        id: 172,
        name: "红山文化玉龙",
        localImage: "172-official.jpg",
        status: "ready",
    },
    173: {
        id: 173,
        name: "马家窑文化彩陶舞蹈纹盆",
        localImage: "173-official.jpg",
        status: "ready",
    },
    174: {
        id: 174,
        name: "马家窑文化彩陶贴塑人纹双系壶",
        localImage: "174-official.jpg",
        status: "ready",
    },
    175: {
        id: 175,
        name: "仰韶文化彩陶网纹船形壶",
        localImage: "175-official.jpg",
        status: "ready",
    },
    176: {
        id: 176,
        name: "仰韶文化彩陶人面鱼纹盆",
        localImage: "176-official.jpg",
        status: "ready",
    },
    177: {
        id: 177,
        name: "绿玻璃盖罐",
        localImage: "177-official.jpg",
        status: "ready",
    },
    178: {
        id: 178,
        name: "绿玻璃小瓶",
        localImage: "178-official.jpg",
        status: "ready",
    },
    179: {
        id: 179,
        name: "陶骆驼载乐舞三彩俑",
        localImage: "179-official.jpg",
        status: "ready",
    },
    180: {
        id: 180,
        name: "诅盟场面贮贝器",
        localImage: "180-official.jpg",
        status: "ready",
    },
    181: {
        id: 181,
        name: "“滇王之印”金印",
        localImage: "181-official.jpg",
        status: "ready",
    },
    182: {
        id: 182,
        name: "天亡簋",
        localImage: "182-official.jpg",
        status: "ready",
    },
    183: {
        id: 183,
        name: "子龙鼎",
        localImage: "183-official.jpg",
        status: "ready",
    },
    184: {
        id: 184,
        name: "孝端皇后凤冠",
        localImage: "184-official.jpg",
        status: "ready",
    },
    185: {
        id: 185,
        name: "后母戊鼎 (旧称司母戊鼎）",
        localImage: "185-houmuwuding-official.jpg",
        status: "ready",
    },
    186: {
        id: 186,
        name: "彩绘鹤鱼石斧图陶缸",
        localImage: "186-official.jpg",
        status: "ready",
    },
    187: {
        id: 187,
        name: "大盂鼎",
        localImage: "187-official.jpg",
        status: "ready",
    },
    188: {
        id: 188,
        name: "虢季子白盘",
        localImage: "188-official.jpg",
        status: "ready",
    },
    189: {
        id: 189,
        name: "陶鹰鼎",
        localImage: "189-official.jpg",
        status: "ready",
    },
    190: {
        id: 190,
        name: "利簋",
        localImage: "190-official.jpg",
        status: "ready",
    },
    191: {
        id: 191,
        name: "刻开宝藏本《阿惟越致经》 (1卷)",
        wikipediaTitle: "西晋刻本《阿惟越致经》",
        status: "ready",
    },
    192: {
        id: 192,
        name: "刻本《范仲淹文集》 (30卷)",
        wikipediaTitle: "北宋刻本《范仲淹文集》",
        status: "ready",
    },
    193: {
        id: 193,
        name: "龙山文化彩绘蟠龙纹陶盘",
        localImage: "taosilongpan.jpg",
        status: "ready",
    },
    194: {
        id: 194,
        name: "嵌绿松石象牙杯",
        wikipediaTitle: "嵌绿松石象牙杯",
        status: "ready",
    },
    195: {
        id: 195,
        name: "齐王墓青铜方镜",
        wikipediaTitle: "齐王墓青铜方镜",
        status: "ready",
    },
};
