import type { ComponentType } from "react";

export interface AppCatalogItem {
    id: string;
    label: string;
    url: string;
    icon: string;
    description: string;
    component: () => Promise<{ default: ComponentType<Record<string, never>> }>;
}

export const appCatalog: AppCatalogItem[] = [
    // {
    //     id: "reading-notes",
    //     label: "读书笔记合集",
    //     url: "/reading-notes",
    //     icon: "material-symbols:auto-stories-outline-rounded",
    //     description: "按书架浏览微信读书笔记，沉浸式查看封面、书摘与章节划线",
    //     component: () => import("./ReadingNotesCollection"),
    // },
    {
        id: "watermark",
        label: "水印添加",
        url: "/watermark",
        icon: "ri:image-ai-line",
        description: "批量给图片加文字或图标水印，快速保护版权",
        component: () => import("./pages/watermark"),
    },
     {
        id: "puzzle",
        label: "长图拼版",
        url: "/puzzle",
        icon: "tabler:layout-board-split",
        description: "多图自由排版后导出长图，适合作品集、教程和图文合集",
        component: () => import("./pages/puzzle"),
    },
    {
        id: "compress",
        label: "批量压缩",
        url: "/compress",
        icon: "material-symbols:compress",
        description: "批量减小图片体积，兼顾清晰度和上传速度",
        component: () => import("./pages/compress"),
    },
    {
        id: "photo",
        label: "Google 相册",
        url: "/google-photo",
        icon: "logos:google-photos",
        description: "按相册流式浏览照片，适合沉浸式回看和筛图",
        component: () => import("./pages/google-photo"),
    },
    {
        id: "cover-collage",
        label: "封面拼贴",
        url: "/cover-collage",
        icon: "material-symbols:imagesmode-outline-rounded",
        description: "上传多张图片生成暗色展陈感 cover 图，适合做封面和分享海报",
        component: () => import("./pages/cover-collage"),
    },
    // {
    //     id: "frame",
    //     label: "简约相框",
    //     url: "/frame",
    //     icon: "ri:image-edit-line",
    //     description: "为照片加统一边框和留白，适合发朋友圈或打印",
    //     component: () => import("./PhotoFrame"),
    // },
    {
        id: "photo-exif",
        label: "照片 EXIF",
        url: "/photo-exif",
        icon: "material-symbols:info-outline-rounded",
        description: "查看和批量修改照片 EXIF 信息，适合整理拍摄元数据",
        component: () => import("./pages/photo-exif"),
    },
    {
        id: "split",
        label: "规则切图",
        url: "/split",
        icon: "material-symbols:split-vertical",
        description: "把一张图按网格或规则切成多张，适合九宫格和分片发布",
        component: () => import("./pages/split"),
    },
    {
        id: "crop",
        label: "尺寸裁切",
        url: "/crop",
        icon: "material-symbols:crop",
        description: "按比例、固定像素或自由框选裁切，快速得到目标尺寸",
        component: () => import("./pages/crop"),
    },
    {
        id: "stitch",
        label: "全景拼接",
        url: "/stitch",
        icon: "material-symbols:photo-library-outline",
        description: "上传有重叠区域的照片自动合成为一张全景大图",
        component: () => import("./pages/stitch"),
    },
    {
        id: "focus-stack",
        label: "焦点合成",
        url: "/focus-stack",
        icon: "mdi:image-filter-hdr",
        description: "把不同对焦点的照片融合成一张尽量全清晰的成片",
        component: () => import("./pages/focus-stack"),
    },
    {
        id: "artifact-ai",
        label: "文物百科",
        url: "/artifact-ai",
        icon: "lucide:book-open",
        description: "输入问题快速查文物背景，适合做讲解和科普笔记",
        component: () => import("./pages/artifact-ai"),
    },
    // {
    //     id: "restaurant",
    //     label: "餐厅搜索",
    //     url: "/restaurant",
    //     icon: "ri:restaurant-2-line",
    //     description: "按位置和偏好筛餐厅，快速决定去哪吃",
    //     component: () => import("./RestaurantFinder"),
    // },
    // {
    //     id: "change",
    //     label: "图片颜色调整",
    //     url: "/change",
    //     icon: "material-symbols:palette-outline",
    //     description: "调亮度、对比度和色调，快速修正照片观感",
    //     component: () => import("./ChangeColor"),
    // },
    {
        id: "wenwu",
        label: "195禁出",
        url: "/wenwu",
        icon: "material-symbols:museum-outline",
        description: "按地图查看重点馆藏与分布，快速了解文物脉络",
        component: () => import("./pages/wenwu"),
    },
    // {
    //     id: "news",
    //     label: "新闻",
    //     url: "/news",
    //     icon: "ri:news-line",
    //     description: "聚合热点资讯，快速浏览当天重要信息",
    //     component: () => import("./News"),
    // },
    {
        id: "collage",
        label: "模板拼贴",
        url: "/collage",
        icon: "material-symbols:photo-library-outline",
        description: "按预设模板合成多图海报，适合电商图、封面和分享图",
        component: () => import("./pages/collage"),
    },
    {
        id: "rename",
        label: "文件重命名",
        url: "/rename",
        icon: "material-symbols:file-rename-outline",
        description: "按规则批量改文件名，整理素材更省时",
        component: () => import("./pages/rename"),
    },
    {
        id: "gallery",
        label: "年度相册",
        url: "/gallery",
        icon: "material-symbols:photo-library-outline",
        description: "做有边框和排版感的年度照片合集，一键导出",
        component: () => import("./pages/gallery"),
    },
    // {
    //     id: "christmas",
    //     label: "圣诞树",
    //     url: "/christmas",
    //     icon: "mdi:pine-tree",
    //     description: "节日互动小工具，适合屏幕展示和氛围装饰",
    //     component: () => import("./ChristmasTreeHand"),
    // },
    {
        id: "calendar",
        label: "日历",
        url: "/calendar",
        icon: "material-symbols:calendar-month-outline",
        description: "大屏日历和时钟展示，适合会议室或工作台",
        component: () => import("./pages/calendar"),
    },
    {
        id: "raw-editor",
        label: "RAW编辑器",
        url: "/raw-editor",
        icon: "material-symbols:camera-enhance-outline",
        description: "面向摄影后期的 RAW 调整工具，精细控制画质",
        component: () => import("./pages/raw-editor"),
    },
    {
        id: "museum",
        label: "博物万象",
        url: "/museum",
        icon: "material-symbols:museum-outline",
        description: "聚合博物馆内容入口，便于浏览专题与展讯",
        component: () => import("./pages/museum"),
    },
    {
        id: "museum-events",
        label: "临展雷达",
        url: "/museum-events",
        icon: "material-symbols:event-available-outline",
        description: "追踪近期临展和时间节点，避免错过想看的展",
        component: () => import("./pages/museum-events"),
    },
];
